import './globals.css'
import {Inter} from 'next/font/google'
import clsx from "clsx";
import Providers from "@/components/Providers";
import {Analytics} from '@vercel/analytics/react';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="pl" data-theme={"retro"}>
        <head>
            <meta name="viewport" content={"initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1"}/>
        </head>
        <body className={clsx(inter.className, 'bg-base-100', 'min-w-screen min-h-screen m-0')}>
        <Providers>
            {children}
            <Analytics/>
        </Providers>
        </body>
        </html>
    )
}
